"""add_password_hash_and_schema_constraints

Revision ID: 3c94c972bba8
Revises: 789c2e44df62
Create Date: 2026-05-03 10:04:20.587922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c94c972bba8'
down_revision: Union[str, None] = '789c2e44df62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_group_festivals_group_festival', 'group_festivals', ['group_id', 'festival_id'])
    op.create_unique_constraint('uq_group_members_group_user', 'group_members', ['group_id', 'user_id'])
    op.create_index('ix_invitations_group_status', 'invitations', ['group_id', 'status'], unique=False)
    op.create_index('ix_performances_festival_start_time', 'performances', ['festival_id', 'start_time'], unique=False)
    op.create_unique_constraint('uq_user_schedules_user_perf_gf', 'user_schedules', ['user_id', 'performance_id', 'group_festival_id'])
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint('uq_user_schedules_user_perf_gf', 'user_schedules', type_='unique')
    op.drop_index('ix_performances_festival_start_time', table_name='performances')
    op.drop_index('ix_invitations_group_status', table_name='invitations')
    op.drop_constraint('uq_group_members_group_user', 'group_members', type_='unique')
    op.drop_constraint('uq_group_festivals_group_festival', 'group_festivals', type_='unique')
    # ### end Alembic commands ###
